feature_cols:
- age
- ind_nuevo
- antiguedad
- indrel
- indrel_1mes
- conyuemp
- tipodom
- cod_prov
- ind_actividad_cliente
- renta
- n_products
- sexo_V
- segmento_02 - PARTICULARES
- segmento_03 - UNIVERSITARIO
- canal_entrada_KAB
- canal_entrada_KAD
- canal_entrada_KAE
- canal_entrada_KAF
- canal_entrada_KAG
- canal_entrada_KAH
- canal_entrada_KAI
- canal_entrada_KAJ
- canal_entrada_KAP
- canal_entrada_KAQ
- canal_entrada_KAR
- canal_entrada_KAT
- canal_entrada_KAZ
- canal_entrada_KBG
- canal_entrada_KCC
- canal_entrada_KDH
- canal_entrada_KEH
- canal_entrada_KFA
- canal_entrada_KFC
- canal_entrada_KFD
- canal_entrada_KFF
- canal_entrada_KFG
- canal_entrada_KFJ
- canal_entrada_KFK
- canal_entrada_KFL
- canal_entrada_KFN
- canal_entrada_KFP
- canal_entrada_KFS
- canal_entrada_KFU
- canal_entrada_KGC
- canal_entrada_KGN
- canal_entrada_KGV
- canal_entrada_KGX
- canal_entrada_KGY
- canal_entrada_KHA
- canal_entrada_KHC
- canal_entrada_KHD
- canal_entrada_KHE
- canal_entrada_KHF
- canal_entrada_KHK
- canal_entrada_KHL
- canal_entrada_KHM
- canal_entrada_KHN
- canal_entrada_KHO
- canal_entrada_RED
- indresi_S
- indext_S
- pais_residencia_AR
- pais_residencia_AT
- pais_residencia_BE
- pais_residencia_BR
- pais_residencia_CA
- pais_residencia_CH
- pais_residencia_CL
- pais_residencia_CN
- pais_residencia_CO
- pais_residencia_CR
- pais_residencia_DE
- pais_residencia_DO
- pais_residencia_EC
- pais_residencia_ES
- pais_residencia_FI
- pais_residencia_FR
- pais_residencia_GB
- pais_residencia_HN
- pais_residencia_IE
- pais_residencia_IN
- pais_residencia_IT
- pais_residencia_MX
- pais_residencia_MZ
- pais_residencia_NI
- pais_residencia_NL
- pais_residencia_PE
- pais_residencia_PL
- pais_residencia_PT
- pais_residencia_SE
- pais_residencia_TW
- pais_residencia_US
- pais_residencia_VE
- tiprel_1mes_I
- tiprel_1mes_P
- indfall_S
- month
- year
- quarter
- tenure_months
- n_active_products
- product_tier_low
- product_tier_medium
- product_tier_none
model_type: LogisticRegression_OneVsRest
random_state: 42
sample_size: 15000
split_strategy: time_based
target_cols:
- ind_ahor_fin_ult1
- ind_aval_fin_ult1
- ind_cco_fin_ult1
- ind_cder_fin_ult1
- ind_cno_fin_ult1
- ind_ctju_fin_ult1
- ind_ctma_fin_ult1
- ind_ctop_fin_ult1
- ind_ctpp_fin_ult1
- ind_deco_fin_ult1
- ind_deme_fin_ult1
- ind_dela_fin_ult1
- ind_ecue_fin_ult1
- ind_fond_fin_ult1
- ind_hip_fin_ult1
- ind_plan_fin_ult1
- ind_pres_fin_ult1
- ind_reca_fin_ult1
- ind_tjcr_fin_ult1
- ind_valo_fin_ult1
- ind_viv_fin_ult1
- ind_nomina_ult1
- ind_nom_pens_ult1
- ind_recibo_ult1
